apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: httpd-hello-mobile
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: httpd-hello-mobile
      app.kubernetes.io/component: httpd-hello-mobile
      app.kubernetes.io/instance: httpd-hello-mobile
    name: httpd-hello-mobile
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: httpd-hello-mobile:latest
    source:
      contextDir: httpd-hello-mobile
      git:
        uri: https://github.com/musanmaz/container-up
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.openshift
        from:
          kind: ImageStreamTag
          name: httpd:2.4
          namespace: openshift
      type: Docker
    triggers:
    - type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: httpd-hello-mobile
      app.kubernetes.io/component: httpd-hello-mobile
      app.kubernetes.io/instance: httpd-hello-mobile
    name: httpd-hello-mobile
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: httpd-hello-mobile
      app.kubernetes.io/component: httpd-hello-mobile
      app.kubernetes.io/instance: httpd-hello-mobile
    name: httpd-hello-mobile
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: httpd-hello-mobile
      weight: 100
    wildcardPolicy: None
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: httpd-hello-mobile
      app.kubernetes.io/component: httpd-hello-mobile
      app.kubernetes.io/instance: httpd-hello-mobile
    name: httpd-hello-mobile
  spec:
    replicas: 1
    selector:
      deploymentconfig: httpd-hello-mobile
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: httpd-hello-mobile
      spec:
        containers:
        - image: httpd-hello-mobile
          imagePullPolicy: Always
          name: httpd-hello-mobile
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
        restartPolicy: Always
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - httpd-hello-mobile
        from:
          kind: ImageStreamTag
          name: httpd-hello-mobile:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: httpd-hello-mobile
      app.kubernetes.io/component: httpd-hello-mobile
      app.kubernetes.io/instance: httpd-hello-mobile
    name: httpd-hello-mobile
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentconfig: httpd-hello-mobile
    type: ClusterIP
parameters:
- description: Name that will be given to all the resources
  displayName: Name
  name: NAME
  required: true
  value: mywebsite
